version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    ports:
        - 5432:5432
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    tty: true
    stdin_open: true
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/exchange-app'
    env_file:
      - '.env'

volumes:
  postgres:
