version: 2
jobs:
  build:
    environment:
      - RAILS_ENV: "test"
      - CI: true
    working_directory: ~/website
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout

      - run:
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Specs
          command: rspec

      - store_artifacts:
          path: coverage/.resultset.json
          prefix: coverage

      - deploy:
          name: Merge and copy coverage data
          command: bundle exec report_coverage
