version: 2
jobs:
  build:
    environment:
      - RAILS_ENV: "test"
      - CI: true
    working_directory: ~/website
    docker:
      - image: enjoei/ruby-ci:2.4.2
    steps:
      - checkout

      - run:
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: precompile
          command: bundle exec rake assets:precompile

      - run:
          name: Specs
          command: bundle exec rspec


      - run:
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          command: bundle exec rake db:create db:structure:load --trace

      - run:
          name: Specs
          command: KNAPSACK_TEST_FILE_PATTERN="spec/**/*_spec.rb" bundle exec rake "knapsack:rspec[--format progress --format RspecJunitFormatter -o ~/rspec/specs.xml]"

      - store_artifacts:
          path: coverage/.resultset.json
          prefix: coverage

      - deploy:
          name: Merge and copy coverage data
          command: bundle exec report_coverage
