version: 2
jobs:
  build:
    environment:
      - RAILS_ENV: "test"
      - CI: true
    working_directory: ~/website
    docker:
      - image: andreleoni/exchange:ci
    steps:
      - checkout

      - run:
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: precompile
          command: bundle exec rake assets:precompile

      - run:
          name: Specs
          command: bundle exec rspec && CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN bundle exec codeclimate-test-reporter
